<x-app-layout>
    <x-slot name="title">Financial Highlights History</x-slot>
    <x-slot name="crumbs">Financial Highlights / History</x-slot>
    <div class="card mb-6"><div class="card-head"><h2>Import History</h2><div class="flex gap-3"><a href="{{ route('financial-highlights.upload') }}" class="btn btn-outline">Upload</a><a href="{{ route('financial-highlights.import') }}" class="btn btn-primary">Import Module</a></div></div><div class="card-body">
        <form method="GET" class="input-row"><div class="field"><label>Financial Year</label><select class="input" name="fiscal_year"><option value="">All Financial Years</option>@foreach($fiscalYears as $year)<option value="{{ $year }}" @selected(request('fiscal_year')===$year)>{{ $year }}</option>@endforeach</select></div><div class="field"><label>Quarter</label><select class="input" name="quarter"><option value="">All Quarters</option>@foreach($quarters as $number=>$label)<option value="{{ $number }}" @selected((int)request('quarter')===$number)>{{ $label }}</option>@endforeach</select></div><div class="field" style="justify-content:end;"><div class="flex gap-3"><button class="btn btn-primary">Filter</button><a href="{{ route('financial-highlights.history') }}" class="btn btn-outline">Reset</a></div></div></form>
    </div></div>
    @forelse($history as $batch)
        <div class="card mb-6"><div class="card-head"><div><h2>{{ $batch->original_file_name }}</h2><div class="text-muted" style="font-size:12px;margin-top:4px;">FY {{ $batch->fiscal_year }} · {{ $quarters[$batch->quarter] }} · {{ $batch->imported_at?->format('Y-m-d H:i') }} · {{ $batch->imported_rows }} row(s)</div></div><form method="POST" action="{{ route('financial-highlights.destroy',$batch) }}" onsubmit="return confirm('Delete this import and all its financial highlight rows?')">@csrf @method('DELETE')<button class="btn btn-ghost" style="color:#DC2626;border:1px solid #FCA5A5;">Delete</button></form></div>
        <div class="table-wrap" style="border:0;"><table class="t"><thead><tr><th>Solvency Ratio (x)</th><th>ROE (%)</th><th>EPS (NPR)</th><th>Net Worth (NPR)</th><th>Profit Margin (%)</th><th>Liquidity Ratio</th><th>Investment Yield (%)</th></tr></thead><tbody>@foreach($batch->highlights as $row)<tr><td>{{ $row->solvency_ratio }}</td><td>{{ $row->return_on_equity }}</td><td>{{ $row->earnings_per_share }}</td><td>{{ $row->net_worth }}</td><td>{{ $row->net_profit_margin }}</td><td>{{ $row->liquidity_ratio }}</td><td>{{ $row->investment_yield }}</td></tr>@endforeach</tbody></table></div></div>
    @empty<div class="card"><div class="card-body text-muted" style="text-align:center;padding:40px;">No imported financial highlights found.</div></div>@endforelse
</x-app-layout>
