<x-app-layout>
    <x-slot name="title">Financial Highlights Import &amp; History</x-slot>
    <x-slot name="crumbs">Financial Highlights / Import &amp; History</x-slot>
    <div class="grid cols-3 mb-6"><div style="grid-column:span 2;"><div class="card"><div class="card-head"><h2>Import to Database</h2><a href="{{ route('financial-highlights.upload') }}" class="btn btn-outline">Upload New File</a></div><div class="card-body">
        @if($errors->has('file'))<div style="background:#FEF2F2;color:#991B1B;padding:12px;border-radius:8px;margin-bottom:16px;">{{ $errors->first('file') }}</div>@endif
        <form method="POST" action="{{ route('financial-highlights.import.store') }}">@csrf
            <div class="field"><label for="import_id">Uploaded File</label><select class="input" id="import_id" name="import_id" required><option value="">Select file</option>@foreach($imports as $item)<option value="{{ $item->id }}" data-year="{{ $item->fiscal_year }}" data-quarter="{{ $quarters[$item->quarter] }}" @selected($selected?->id === $item->id)>{{ $item->original_file_name }} — FY {{ $item->fiscal_year }}, {{ $quarters[$item->quarter] }}</option>@endforeach</select></div>
            @if($selected?->error_message)<div style="background:#FEF2F2;color:#991B1B;padding:12px;border-radius:8px;margin-top:14px;">Previous error: {{ $selected->error_message }}</div>@endif
            <div class="grid cols-2 mt-4"><div class="kpi"><div class="label">Financial Year</div><div class="value" id="yearValue">{{ $selected?->fiscal_year ?? '-' }}</div></div><div class="kpi"><div class="label">Quarter</div><div class="value" id="quarterValue">{{ $selected ? $quarters[$selected->quarter] : '-' }}</div></div></div>
            <div class="flex gap-3 mt-4"><button class="btn btn-primary" @disabled(!$selected)>Import Financial Highlights</button><a href="#import-history" class="btn btn-outline">Jump to History</a></div>
        </form>
    </div></div></div><div class="card"><div class="card-head"><h2>Import Process</h2></div><div class="card-body text-muted" style="font-size:13px;line-height:1.8;">The selected financial year and quarter are stored on every imported row. Failed files remain available here so they can be corrected, uploaded again, or retried.</div></div></div>
    <div class="card mb-6" id="import-history"><div class="card-head"><h2>Import History</h2><span class="badge info">{{ $history->count() }} import(s)</span></div><div class="card-body">
        <form method="GET" action="{{ route('financial-highlights.import') }}" class="input-row"><div class="field"><label>Financial Year</label><select class="input" name="fiscal_year"><option value="">All Financial Years</option>@foreach($fiscalYears as $year)<option value="{{ $year }}" @selected(request('fiscal_year')===$year)>{{ $year }}</option>@endforeach</select></div><div class="field"><label>Quarter</label><select class="input" name="quarter"><option value="">All Quarters</option>@foreach($quarters as $number=>$label)<option value="{{ $number }}" @selected((int)request('quarter')===$number)>{{ $label }}</option>@endforeach</select></div><div class="field" style="justify-content:end;"><div class="flex gap-3"><button class="btn btn-primary">Filter</button><a href="{{ route('financial-highlights.import') }}#import-history" class="btn btn-outline">Reset</a></div></div></form>
    </div></div>
    @forelse($history as $batch)
        <div class="card mb-6"><div class="card-head"><div><h2>{{ $batch->original_file_name }}</h2><div class="text-muted" style="font-size:12px;margin-top:4px;">FY {{ $batch->fiscal_year }} · {{ $quarters[$batch->quarter] }} · {{ $batch->imported_at?->format('Y-m-d H:i') }} · {{ $batch->imported_rows }} row(s)</div></div><form method="POST" action="{{ route('financial-highlights.destroy',$batch) }}" onsubmit="return confirm('Delete this import and all its financial highlight rows?')">@csrf @method('DELETE')<button class="btn btn-ghost" style="color:#DC2626;border:1px solid #FCA5A5;">Delete</button></form></div>
        <div class="table-wrap" style="border:0;"><table class="t"><thead><tr><th>Solvency Ratio (x)</th><th>ROE (%)</th><th>EPS (NPR)</th><th>Net Worth (NPR)</th><th>Profit Margin (%)</th><th>Liquidity Ratio</th><th>Investment Yield (%)</th></tr></thead><tbody>@foreach($batch->highlights as $row)<tr><td>{{ $row->solvency_ratio }}</td><td>{{ $row->return_on_equity }}</td><td>{{ $row->earnings_per_share }}</td><td>{{ $row->net_worth }}</td><td>{{ $row->net_profit_margin }}</td><td>{{ $row->liquidity_ratio }}</td><td>{{ $row->investment_yield }}</td></tr>@endforeach</tbody></table></div></div>
    @empty<div class="card"><div class="card-body text-muted" style="text-align:center;padding:40px;">No imported financial highlights found.</div></div>@endforelse
    <script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('import_id'),y=document.getElementById('yearValue'),q=document.getElementById('quarterValue');s.addEventListener('change',()=>{const o=s.options[s.selectedIndex];y.textContent=o?.dataset.year||'-';q.textContent=o?.dataset.quarter||'-';});});</script>
</x-app-layout>
